language: ruby
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.0
cache: bundler
script:
  - bundle exec rspec
services:
    - postgresql
addons:
  postgresql: "9.1"
env:
  - RSPEC_VERSION="<2.99"
  - RSPEC_VERSION="~>3.0
